### ISSUE TITLE
wordlist directory wasn't created 

### ISSUE THREAD

**Issue by ramysaafan17** [xyele/hackerone_wordlist#1]
**Describe the bug**
by running the command "python3 create_wordlist.py --dataset dataset.csv --output wordlists/ --entropy 4" 
it gives the following error , Had to create it first then rerun the command again
![image](https://user-images.githubusercontent.com/27290152/85952554-6297aa00-b96a-11ea-85a6-795de739cd27.png)

**Your Enviroement**
 - OS [ Ubuntu 20.04]
 - Version [e.g. 1.0]
 - Python Version [3.8.2

**Comment by xyele** [comment]
Oh looks like I forgot the code that creates the wordlists directory. So can you please try creating a directory which named as wordlists first?
